
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-compiler-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.1.0
 * Query Engine version: ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba
 */
Prisma.prismaVersion = {
  client: "7.1.0",
  engine: "ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.LeadScalarFieldEnum = {
  id: 'id',
  channel: 'channel',
  contact: 'contact',
  createdAt: 'createdAt'
};

exports.Prisma.LandingContentScalarFieldEnum = {
  id: 'id',
  headerPhrase: 'headerPhrase',
  heroImage: 'heroImage',
  heroHeading: 'heroHeading',
  heroDescription: 'heroDescription',
  heroSupport: 'heroSupport',
  buttonLabel: 'buttonLabel',
  contact: 'contact',
  videoUrl: 'videoUrl',
  nextScreenTitle: 'nextScreenTitle',
  nextScreenDescription: 'nextScreenDescription',
  nextScreenQuestion: 'nextScreenQuestion',
  telegramEnabled: 'telegramEnabled',
  whatsappEnabled: 'whatsappEnabled',
  customScript: 'customScript',
  notificationEmail: 'notificationEmail',
  logoPath: 'logoPath',
  notificationFrom: 'notificationFrom',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.Channel = exports.$Enums.Channel = {
  whatsapp: 'whatsapp',
  telegram: 'telegram'
};

exports.Prisma.ModelName = {
  Lead: 'Lead',
  LandingContent: 'LandingContent'
};
/**
 * Create the Client
 */
const config = {
  "previewFeatures": [],
  "clientVersion": "7.1.0",
  "engineVersion": "ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba",
  "activeProvider": "postgresql",
  "inlineSchema": "generator client {\n  provider = \"prisma-client-js\"\n  output   = \"../generated-prisma-client\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n}\n\nenum Channel {\n  whatsapp\n  telegram\n}\n\nmodel Lead {\n  id        String   @id @default(cuid())\n  channel   Channel\n  contact   String\n  createdAt DateTime @default(now())\n}\n\nmodel LandingContent {\n  id                    String   @id\n  headerPhrase          String\n  heroImage             String?\n  heroHeading           String\n  heroDescription       String\n  heroSupport           String\n  buttonLabel           String\n  contact               String\n  videoUrl              String\n  nextScreenTitle       String\n  nextScreenDescription String\n  nextScreenQuestion    String\n  telegramEnabled       Boolean  @default(true)\n  whatsappEnabled       Boolean  @default(true)\n  customScript          String?\n  notificationEmail     String   @default(\"pc-move@gmail.com\")\n  logoPath              String   @default(\"/assets/images/logo.webp\")\n  notificationFrom      String   @default(\"pc-move@gmail.com\")\n  createdAt             DateTime @default(now())\n  updatedAt             DateTime @updatedAt\n}\n"
}

config.runtimeDataModel = JSON.parse("{\"models\":{\"Lead\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"channel\",\"kind\":\"enum\",\"type\":\"Channel\"},{\"name\":\"contact\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":null},\"LandingContent\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"headerPhrase\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"heroImage\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"heroHeading\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"heroDescription\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"heroSupport\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"buttonLabel\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"contact\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"videoUrl\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"nextScreenTitle\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"nextScreenDescription\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"nextScreenQuestion\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"telegramEnabled\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"whatsappEnabled\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"customScript\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"notificationEmail\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"logoPath\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"notificationFrom\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"updatedAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.compilerWasm = {
  getRuntime: async () => require('./query_compiler_bg.js'),
  getQueryCompilerWasmModule: async () => {
    const loader = (await import('#wasm-compiler-loader')).default
    const compiler = (await loader).default
    return compiler
  }
}
if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || (typeof process !== 'undefined' && process.env && process.env.DEBUG) || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || (typeof process !== 'undefined' && process.env && process.env.DEBUG) || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)
